// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  validation: {
    errorGeneric: 'Something went wrong. Please try again.';
    errorValidation: 'Validation failed.';

    required: 'Please enter {object}';
    password: 'At least {totalCharCount, plural, =1 {# character} other {# characters}} with {specialCharCount, plural, =1 {# special character} other {# special characters}}';
    objectInvalid: 'Invalid {object}';
    min: {
      character: 'At least {count, plural, =1 {# character} other {# characters}}.';
    };
    max: {
      character: 'At most {count, plural, =1 {# character} other {# characters}}.';
    };
  };
  errorBoundary: {
    title: 'Something went wrong';
    subtitle: 'An unexpected error occurred. Please try again.';
    tryAgain: 'Try again';
  };
  components: {
    simpleEmpty: {
      noData: 'Nothing here yet';
    };
    confirmDialog: {
      title: 'Are you sure?';
      content: 'This action cannot be undone';
      confirmText: 'Confirm';
      cancelText: 'Cancel';
    };
  };
  layout: {
    nav: {
      dashboard: 'Dashboard';
      trackerBoard: 'Tracker Board';
      resumeLibrary: 'Resume Library';
      settings: 'Settings';
      tags: 'Tags';
      subStages: 'Sub-stages';
      notification: 'Notification';
    };
    jobHuntSwitcher: {
      activeJobHunt: 'Active hunt';
      jobHunts: 'Job Hunts';
      startJobHunt: 'Start a hunt';
    };
    navUser: {
      signOut: 'Sign out';
    };
  };
  auth: {
    shared: {
      email: 'Email';
      emailPlaceholder: 'name@example.com';
      password: 'Password';
      passwordPlaceholder: 'Enter your password';
      google: 'Log in with Google';
      github: 'Log in with GitHub';
      or: 'or';
      checkEmailTitle: 'Check your email';
      checkEmailSubtitle: 'We just sent a verification link to {email}.';
      resendEmail: 'Resend email';
      resendEmailSuccess: 'Verification email sent.';

      errorInvalidCredentials: 'Invalid email or password.';
      errorInvalidToken: 'This reset link is invalid or has expired.';
    };
    signIn: {
      submit: 'Log in';
    };
    signUp: {
      submit: 'Create account';
      goToLogin: 'Go to login';
    };
    resetPassword: {
      submit: 'Send reset instructions';
      resetCheckEmailTitle: 'Check your email';
      resetCheckEmailSubtitle: "If an account exists for {email}, we've sent password reset instructions.";
    };
    newPassword: {
      label: 'New password';
      placeholder: 'Enter a new password';
      confirmLabel: 'Confirm password';
      confirmPlaceholder: 'Re-enter your new password';
      submit: 'Reset password';
      passwordsMustMatch: "Passwords don't match";
      resetSuccess: 'Your password has been reset. Please log in.';
    };
  };
};
export default messages;
